### ISSUE TITLE
idea mpx plugin exception

### ISSUE THREAD

**Issue by junxiongchu** [didi/mpx#1162]
1. java.lang.ClassCastException: class java.lang.String cannot be cast to class com.intellij.webSymbols.WebSymbolQualifiedName (java.lang.String is in module java.base of loader 'bootstrap'; com.intellij.webSymbols.WebSymbolQualifiedName is in unnamed module of loader com.intellij.util.lang.PathClassLoader @224aed64)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runQuery$lambda$9(WebSymbolsQueryExecutorImpl.kt:171)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runQuery(WebSymbolsQueryExecutorImpl.kt:167)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runNameMatchQuery$intellij_platform_webSymbols(WebSymbolsQueryExecutorImpl.kt:79)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runNameMatchQuery(WebSymbolsQueryExecutorImpl.kt:63)
	at com.intellij.html.webSymbols.elements.WebSymbolElementDescriptor.runNameMatchQuery(WebSymbolElementDescriptor.kt:49)
	at com.intellij.html.webSymbols.elements.WebSymbolElementDescriptor.runNameMatchQuery$default(WebSymbolElementDescriptor.kt:44)
	at com.hxz.mpxjs.model.VueSlotUtilsKt.getSlots(VueSlotUtils.kt:54)
	at com.hxz.mpxjs.model.VueSlotUtilsKt.getAvailableSlots(VueSlotUtils.kt:27)
	at com.hxz.mpxjs.web.VueDeprecatedSlotAttributeReferenceProvider.getSymbol(VueDeprecatedSlotAttributeReferenceProvider.kt:22)
	at com.hxz.mpxjs.web.VueDeprecatedSlotAttributeReferenceProvider.getSymbol(VueDeprecatedSlotAttributeReferenceProvider.kt:12)
	at com.intellij.webSymbols.references.WebSymbolReferenceProvider.getOffsetsToSymbols(WebSymbolReferenceProvider.kt:48)
	at com.intellij.webSymbols.references.WebSymbolReferenceProvider.getReferences(WebSymbolReferenceProvider.kt:56)
	at com.intellij.webSymbols.references.WebSymbolReferenceProvider.getReferences$lambda$0(WebSymbolReferenceProvider.kt:37)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.webSymbols.references.WebSymbolReferenceProvider.getReferences(WebSymbolReferenceProvider.kt:35)
	at com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl.doGetExternalReferences(PsiSymbolReferenceServiceImpl.java:68)
	at com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl.getReferences(PsiSymbolReferenceServiceImpl.java:45)
	at com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl.getReferences(PsiSymbolReferenceServiceImpl.java:38)
	at com.intellij.webSymbols.inspections.WebSymbolsInspectionsPass.doCollectInformation(WebSymbolsInspectionsPass.kt:52)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:370)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:346)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:173)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:344)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

2.  java.lang.ClassCastException: class java.lang.String cannot be cast to class com.intellij.webSymbols.WebSymbolQualifiedName (java.lang.String is in module java.base of loader 'bootstrap'; com.intellij.webSymbols.WebSymbolQualifiedName is in unnamed module of loader com.intellij.util.lang.PathClassLoader @224aed64)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runQuery$lambda$9(WebSymbolsQueryExecutorImpl.kt:171)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runQuery(WebSymbolsQueryExecutorImpl.kt:167)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runNameMatchQuery$intellij_platform_webSymbols(WebSymbolsQueryExecutorImpl.kt:79)
	at com.intellij.webSymbols.query.impl.WebSymbolsQueryExecutorImpl.runNameMatchQuery(WebSymbolsQueryExecutorImpl.kt:63)
	at com.intellij.html.webSymbols.elements.WebSymbolElementDescriptor.runNameMatchQuery(WebSymbolElementDescriptor.kt:49)
	at com.intellij.html.webSymbols.elements.WebSymbolElementDescriptor.runNameMatchQuery$default(WebSymbolElementDescriptor.kt:44)
	at com.hxz.mpxjs.model.VueSlotUtilsKt.getSlots(VueSlotUtils.kt:54)
	at com.hxz.mpxjs.model.VueSlotUtilsKt.getAvailableSlots(VueSlotUtils.kt:27)
	at com.hxz.mpxjs.web.VueDeprecatedSlotAttributeReferenceProvider.getSymbol(VueDeprecatedSlotAttributeReferenceProvider.kt:22)
	at com.hxz.mpxjs.web.VueDeprecatedSlotAttributeReferenceProvider.getSymbol(VueDeprecatedSlotAttributeReferenceProvider.kt:12)
	at com.intellij.webSymbols.references.WebSymbolReferenceProvider.getOffsetsToSymbols(WebSymbolReferenceProvider.kt:48)
	at com.intellij.webSymbols.references.WebSymbolReferenceProvider.getReferences(WebSymbolReferenceProvider.kt:56)
	at com.intellij.webSymbols.references.WebSymbolReferenceProvider.getReferences$lambda$0(WebSymbolReferenceProvider.kt:37)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.webSymbols.references.WebSymbolReferenceProvider.getReferences(WebSymbolReferenceProvider.kt:35)
	at com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl.doGetExternalReferences(PsiSymbolReferenceServiceImpl.java:68)
	at com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl.getReferences(PsiSymbolReferenceServiceImpl.java:45)
	at com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl.getReferences(PsiSymbolReferenceServiceImpl.java:38)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:34)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:344)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:283)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:304)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:607)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:222)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:370)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:346)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:173)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:344)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

mpx plugin 版本：1.3
idea ide 版本: IU-223.8214.52

**Comment by junxiongchu** [comment]
@wuxianqiang

**Comment by wuxianqiang** [comment]
> @wuxianqiang

简单描述一下你的操作步骤吧，我本地尝试没有这样的报错。如果是启动报错，需要你提供一个简单的复现demo

**Comment by junxiongchu** [comment]
> > @wuxianqiang
> 
> 简单描述一下你的操作步骤吧，我本地尝试没有这样的报错。如果是启动报错，需要你提供一个简单的复现demo

今天升级到1.4版本后，没有再启动打开mpx文件后报错了，但是有个新问题，idea 依然会对mpx里的style css value的单位rp进行错误标红，显示类似：Mismatched property value ([<length> | <percentage> | fill | auto] | [initial | inherit | unset | revert])这种。

**Comment by wuxianqiang** [comment]
> > > @wuxianqiang
> > 
> > 
> > 简单描述一下你的操作步骤吧，我本地尝试没有这样的报错。如果是启动报错，需要你提供一个简单的复现demo
> 
> 今天升级到1.4版本后，没有再启动打开mpx文件后报错了，但是有个新问题，idea 依然会对mpx里的style css value的单位rpx进行错误标红，显示类似：Mismatched property value ([ | | fill | auto] | [initial | inherit | unset | revert])这种错误提示。

问题已经修复了，将插件升级到1.5版本

**Comment by junxiongchu** [comment]
> > > > @wuxianqiang
> > > 
> > > 
> > > 简单描述一下你的操作步骤吧，我本地尝试没有这样的报错。如果是启动报错，需要你提供一个简单的复现demo
> > 
> > 
> > 今天升级到1.4版本后，没有再启动打开mpx文件后报错了，但是有个新问题，idea 依然会对mpx里的style css value的单位rpx进行错误标红，显示类似：Mismatched property value ([ | | fill | auto] | [initial | inherit | unset | revert])这种错误提示。
> 
> 问题已经修复了，将插件升级到1.5版本

嗯，升级到1.5版本后 rpx错误提示已经没了，但是还有一个新问题，插件貌似还不支持webpack的alias配置，如果代码里有类似import { xxx } from '@/xxx/xxx' 这种导入语句的话 idea也会错误标红。有时间大佬可以看看这个问题。

**Comment by wuxianqiang** [comment]
> > > > > @wuxianqiang
> > > > 
> > > > 
> > > > 简单描述一下你的操作步骤吧，我本地尝试没有这样的报错。如果是启动报错，需要你提供一个简单的复现demo
> > > 
> > > 
> > > 今天升级到1.4版本后，没有再启动打开mpx文件后报错了，但是有个新问题，idea 依然会对mpx里的style css value的单位rpx进行错误标红，显示类似：Mismatched property value ([ | | fill | auto] | [initial | inherit | unset | revert])这种错误提示。
> > 
> > 
> > 问题已经修复了，将插件升级到1.5版本
> 
> 嗯，升级到1.5版本后 rpx错误提示已经没了，但是还有一个新问题，插件貌似还不支持webpack的alias配置，如果代码里有类似import { xxx } from '@/xxx/xxx' 这种导入语句的话 idea也会错误标红。有时间大佬可以看看这个问题。

这个问题是1.5版本导致的，我在1.6修复了，你更新一下插件

**Comment by wuxianqiang** [comment]
关于style属性解析问题我这边可以加下配置，但是路径别名"src="@/styles/xxx.scss"这种无法识别，暂时无法实现，由于编辑器没有提供相关的API，建议先使用相对路径代替。
