### ISSUE TITLE
Json path <componentGenerics> is not supported in ali environment!

### ISSUE THREAD

**Issue by zhoujinfu** [didi/mpx#1273]
```shell
Json path <componentGenerics> is not supported in ali environment!
    at emitError (/Users/edy/Gitlab/mvp-mpx/node_modules/@mpxjs/webpack-plugin/lib/json-compiler/index.js:55:7)
    at print (/Users/edy/Gitlab/mvp-mpx/node_modules/@mpxjs/webpack-plugin/lib/platform/json/wx/index.js:13:15)
    at Object.ali (/Users/edy/Gitlab/mvp-mpx/node_modules/@mpxjs/webpack-plugin/lib/platform/json/wx/index.js:27:9)
    at runRules (/Users/edy/Gitlab/mvp-mpx/node_modules/@mpxjs/webpack-plugin/lib/platform/run-rules.js:30:32)
    at /Users/edy/Gitlab/mvp-mpx/node_modules/@mpxjs/webpack-plugin/lib/platform/index.js:18:16
    at Object.module.exports (/Users/edy/Gitlab/mvp-mpx/node_modules/@mpxjs/webpack-plugin/lib/json-compiler/index.js:197:5)

```

https://opendocs.alipay.com/mini/06mket

alipay 已支持 抽象节点 , 能否添加

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.8.49，已修复
