### ISSUE TITLE
微信小程序引入WeUI，build构建时报错

### ISSUE THREAD

**Issue by jackrouse** [didi/mpx#473]
**问题描述**  

1. app.mpx中通引入<style src="weui-miniprogram/miniprogram_dist/weui-wxss/dist/style/weui.wxss">
</style>，build时会报错。
2. 期望能正常构建
3. 实际的表现
ERROR in ./node_modules/weui-miniprogram/miniprogram_dist/weui-wxss/dist/style/weui.wxss (./node_modules/@mpxjs/webpack-plugin/lib/extractor.js?type=styles&index=-1&issuerResource=D:/workspace/mpx-template/src/app.mpx!./node_modules/@mpxjs/webpack-plugin/lib/wxss/loader.js?root=&importLoaders=1&extract=true!./node_modules/@mpxjs/webpack-plugin/lib/style-compiler?{"moduleId":"m0ce83202","scoped":false,"sourceMap":false}!./node_modules/weui-miniprogram/miniprogram_dist/weui-wxss/dist/style/weui.wxss)
Module build failed (from ./node_modules/@mpxjs/webpack-plugin/lib/wxss/loader.js):
TypeError: Cannot read property 'toFixed' of undefined
    at strongRound (D:\workspace\mpx-template\node_modules\svgo\plugins\convertPathData.js:766:21)
    at D:\workspace\mpx-template\node_modules\svgo\plugins\convertPathData.js:424:17
    at Array.filter (<anonymous>)
    at filters (D:\workspace\mpx-template\node_modules\svgo\plugins\convertPathData.js:272:17)
    at Object.exports.fn (D:\workspace\mpx-template\node_modules\svgo\plugins\convertPathData.js:79:20)
    at D:\workspace\mpx-template\node_modules\svgo\lib\svgo\plugins.js:59:45
    at Array.filter (<anonymous>)
    at monkeys (D:\workspace\mpx-template\node_modules\svgo\lib\svgo\plugins.js:46:39)
    at D:\workspace\mpx-template\node_modules\svgo\lib\svgo\plugins.js:66:17
    at Array.filter (<anonymous>)
    at monkeys (D:\workspace\mpx-template\node_modules\svgo\lib\svgo\plugins.js:46:39)
    at perItem (D:\workspace\mpx-template\node_modules\svgo\lib\svgo\plugins.js:77:12)
    at D:\workspace\mpx-template\node_modules\svgo\lib\svgo\plugins.js:18:24
    at Array.forEach (<anonymous>)
    at module.exports (D:\workspace\mpx-template\node_modules\svgo\lib\svgo\plugins.js:14:13)
    at D:\workspace\mpx-template\node_modules\svgo\lib\svgo.js:63:17
 @ ./src/app.mpx 6:0-424

  Build failed with errors.

感觉是svgo处理压缩weui.wxss导致的报错

**环境信息描述**  
主要依赖版本：
1. 系统类型Windows
2. "@mpxjs/api-proxy": "^2.5.10",
    "@mpxjs/core": "^2.5.11",
    "weui-miniprogram": "^1.0.3"，
    "@mpxjs/webpack-plugin": "^2.5.11",

**Comment by hiyuki** [comment]
确实是svgo处理的问题，我下个版本把svgo关掉吧

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.5.21 已修复
