### ISSUE TITLE
[Bug report] 不支持通过 useExtendedLib 引入 WeUI 

### ISSUE THREAD

**Issue by jissin** [didi/mpx#537]
## 问题触发的条件：
1. 在 app.mpx 中配置
```
  "useExtendedLib": {
    "weui": true
  }
```
2. 在页面的 json 文件的 usingComponents 引入相关 WeUI 组件时，编译无法通过，原因是找不到组件对应的文件。所以我推测 mpx 目前是不支持通过 useExtendedLib 引入 WeUI 的，希望能 cover 一下这种情况，毕竟能减少包体积

**Comment by sky-admin** [comment]
支持的

**Comment by sky-admin** [comment]
@zhaoyiming0803 来给他个例子？

**Comment by zhaoyiming0803** [comment]
目前仅支持微信小程序 weui 组件库通过 useExtendedLib 扩展库的方式引入，这种方式引入的组件将不会计入代码包大小。配置 externals 选项，Mpx 将不会解析 weui 组件的路径并打包。

``` javascript
  // Mpx 配置文件中添加如下配置：
  {
    externals: ['weui']
  }
  ```

  ``` html
  <script name="json">
    // app.mpx json部分
    module.exports = {
      "useExtendedLib": {
        "weui": true
      }
    }
  </script>
  ```

  ``` html
  <!-- 在 page 中使用 weui 组件 -->
  <template>
    <view wx:if="{{__mpx_mode__ === 'wx'}}">
      <mp-icon icon="play" color="black" size="{{25}}" bindtap="showDialog"></mp-icon>
      <mp-dialog title="test" show="{{dialogShow}}" bindbuttontap="tapDialogButton" buttons="{{buttons}}">
        <view>test content</view>
      </mp-dialog>
    </view>
  </template>

  <script>
    import{ createPage } from '@mpxjs/core'

    createPage({
      data: {
        dialogShow: false,
        showOneButtonDialog: false,
        buttons: [{text: '取消'}, {text: '确定'}],
      },
      methods: {
        tapDialogButton () {
          this.dialogShow = false
          this.showOneButtonDialog = false
        },
        showDialog () {
          this.dialogShow = true
        }
      }
    })
  </script>

  <script name="json">
    const wxComponents = {
      "mp-icon": "weui-miniprogram/icon/icon",
      "mp-dialog": "weui-miniprogram/dialog/dialog"
    }
    module.exports = {
      "usingComponents": __mpx_mode__ === 'wx'
        ? Object.assign({}, wxComponents)
        : {}
    }
  </script>
  ```

参考：<a href="https://developers.weixin.qq.com/miniprogram/dev/extended/weui/quickstart.html" target="_blank">weui组件库</a>

**Comment by zhaoyiming0803** [comment]
> ## 问题触发的条件：
> 1. 在 app.mpx 中配置
> 
> ```
>   "useExtendedLib": {
>     "weui": true
>   }
> ```
> 
> 1. 在页面的 json 文件的 usingComponents 引入相关 WeUI 组件时，编译无法通过，原因是找不到组件对应的文件。所以我推测 mpx 目前是不支持通过 useExtendedLib 引入 WeUI 的，希望能 cover 一下这种情况，毕竟能减少包体积

使用文档可参考：https://www.mpxjs.cn/api/compile.html#externals

**Comment by iamcyw** [comment]
> > ## 问题触发的条件：
> > 
> > 1. 在 app.mpx 中配置
> > 
> > ```
> >   "useExtendedLib": {
> >     "weui": true
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. 在页面的 json 文件的 usingComponents 引入相关 WeUI 组件时，编译无法通过，原因是找不到组件对应的文件。所以我推测 mpx 目前是不支持通过 useExtendedLib 引入 WeUI 的，希望能 cover 一下这种情况，毕竟能减少包体积
> 
> 使用文档可参考：https://www.mpxjs.cn/api/compile.html#externals

```
 ERROR  Failed to compile with 2 errors                                                 7:56:11 PM

 error  in ./src/pages/index.mpx?asScript&extract&index=0&isFirst&isPage&mpx=mpx_processed&type=json

Syntax Error: Error: Can't resolve 'weui-miniprogram/cells/cells' in '/Users/iamcyw/SourceCode/city-share/mpx-city-share/src/pages'


 error  in ./src/pages/index.mpx?asScript&extract&index=0&isFirst&isPage&mpx&type=json

Syntax Error: HookWebpackError: Module build failed (from ./node_modules/@mpxjs/webpack-plugin/lib/json-compiler/index.js):
Error: Can't resolve 'weui-miniprogram/cells/cells' in '/Users/iamcyw/SourceCode/city-share/mpx-city-share/src/pages'
-- inner error --
Error: Module build failed (from ./node_modules/@mpxjs/webpack-plugin/lib/json-compiler/index.js):
Error: Can't resolve 'weui-miniprogram/cells/cells' in '/Users/iamcyw/SourceCode/city-share/mpx-city-share/src/pages'
Generated code for /Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/@mpxjs/webpack-plugin/lib/json-compiler/index.js!/Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/@mpxjs/webpack-plugin/lib/selector.js?mode=wx&env=!/Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/windicss-webpack-plugin/dist/loaders/windicss-template.cjs!/Users/iamcyw/SourceCode/city-share/mpx-city-share/src/pages/index.mpx?asScript&extract&index=0&isFirst&isPage&mpx=mpx_processed&type=json
1 | throw new Error("Module build failed (from ./node_modules/@mpxjs/webpack-plugin/lib/json-compiler/index.js):\nError: Can't resolve 'weui-miniprogram/cells/cells' in '/Users/iamcyw/SourceCode/city-share/mpx-city-share/src/pages'\n    at finishWithoutResolve (/Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/enhanced-resolve/lib/Resolver.js:309:18)\n    at /Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/enhanced-resolve/lib/Resolver.js:386:15\n    at /Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/enhanced-resolve/lib/Resolver.js:435:5\n    at eval (eval at create (/Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)\n    at /Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/enhanced-resolve/lib/Resolver.js:435:5\n    at eval (eval at create (/Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)\n    at /Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43\n    at /Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/enhanced-resolve/lib/Resolver.js:435:5\n    at eval (eval at create (/Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n    at /Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/enhanced-resolve/lib/Resolver.js:435:5\n    at eval (eval at create (/Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)\n    at /Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/enhanced-resolve/lib/Resolver.js:435:5\n    at eval (eval at create (/Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:57:1)\n    at /Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/enhanced-resolve/lib/ConditionalPlugin.js:53:42\n    at /Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/enhanced-resolve/lib/Resolver.js:435:5\n    at eval (eval at create (/Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)\n    at /Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/enhanced-resolve/lib/forEachBail.js:16:12\n    at /Users/iamcyw/SourceCode/city-share/mpx-city-share/node_modules/enhanced-resolve/lib/ModulesInHierarchicalDirectoriesPlugin.js:72:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)");

```

使用mpx-cli创建的项目按照这个配置使用weui报错
