### ISSUE TITLE
公共组件webpack打包问题

### ISSUE THREAD

**Issue by tliwyl** [didi/mpx#538]
**问题描述**  

多个分包引用同一.mpx编写组件且js|ts 为外部引入时只有第一个加载该组件的分包能正常运行。例如，a,b两个页面位于不同分包下，我先进入a页面在进入b页面b页面会报错，反之a页面报错

list.mpx 文件代码如下
```
<template>
  <view class="list">
    <view wx:for="{{listData}}" wx:key="index">{{item}}</view>
  </view>
</template>

<script lang="ts" src="./list.ts"></script>

<style lang="stylus">
  .list
    background-color red
</style>

<script type="application/json">
  {
    "component": true
  }
</script>
```
list.ts
```
import { createComponent } from '@mpxjs/core'

createComponent({
  data: {
    listData: ['手机', '电视', '电脑']
  }
})

```

报错如下：
```
jsEnginScriptError
Component is not found in path "packCenter/components/list5b238f42/list" (using by "packCenter/pages/orderDetail/index");onAppRoute
Error: Component is not found in path "packCenter/components/list5b238f42/list" (using by "packCenter/pages/orderDetail/index")
    at K (WAService.js:1:1214064)
    at K (WAService.js:1:1214268)
    at WAService.js:1:1232006
    at Module.Fe (WAService.js:1:1232585)
    at Function.value (WAService.js:1:1260806)
    at It (WAService.js:1:1276660)
    at xt (WAService.js:1:1279059)
    at Function.<anonymous> (WAService.js:1:1284536)
    at i.<anonymous> (WAService.js:1:1253492)
    at i.emit (WAService.js:1:412028)
```

打包出来dist目下在两个分包分都有一份list组件的代码

<img width="375" alt="屏幕快照 2020-08-10 上午11 49 31" src="https://user-images.githubusercontent.com/22835834/89750758-eadba400-daff-11ea-8efe-fb0ac738eee1.png">

<img width="252" alt="屏幕快照 2020-08-10 上午11 52 48" src="https://user-images.githubusercontent.com/22835834/89750817-1fe7f680-db00-11ea-8050-f9f1774287a4.png">

打包出来.wxml和wxss文件没问题js文件内容如下
```

var window = window || {};

window["webpackJsonp"] = require("../../../bundle.js");
(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["packShop/components/list5b238f42/list"],{

/***/ "./node_modules/@mpxjs/webpack-plugin/lib/extractor.js?type=json&index=0!./node_modules/@mpxjs/webpack-plugin/lib/json-compiler/index.js?root=!./node_modules/@mpxjs/webpack-plugin/lib/selector.js?type=json&index=0!./src/components/list/list.mpx?packageName=packShop":
/***/ (function(module, exports) {

// removed by extractor

/***/ }),

/***/ "./node_modules/@mpxjs/webpack-plugin/lib/extractor.js?type=styles&index=0!./node_modules/@mpxjs/webpack-plugin/lib/wxss/loader.js?root=&importLoaders=1&extract=true!./node_modules/@mpxjs/webpack-plugin/lib/style-compiler/index.js?{\"moduleId\":\"m11703cf3\",\"scoped\":false,\"sourceMap\":false}!./node_modules/stylus-loader/index.js!./node_modules/@mpxjs/webpack-plugin/lib/selector.js?type=styles&index=0!./src/components/list/list.mpx?packageName=packShop":
/***/ (function(module, exports) {

// removed by extractor

/***/ }),

/***/ "./node_modules/@mpxjs/webpack-plugin/lib/extractor.js?type=template&index=0!./node_modules/@mpxjs/webpack-plugin/lib/wxml/wxml-loader.js?root=!./node_modules/@mpxjs/webpack-plugin/lib/template-compiler/index.js?{\"usingComponents\":[],\"hasScoped\":false,\"isNative\":false,\"moduleId\":\"m11703cf3\",\"root\":\"\"}!./node_modules/@mpxjs/webpack-plugin/lib/selector.js?type=template&index=0!./src/components/list/list.mpx?packageName=packShop":
/***/ (function(module, exports) {

// removed by extractor

/***/ }),

/***/ "./src/components/list/list.mpx?packageName=packShop":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* WEBPACK VAR INJECTION */(function(global) {/* mpx inject */ global.currentModuleId = "m11703cf3"
global.currentResource = "/Users/litao/work/GM/gome/src/components/list/list.mpx"
global.currentCtor = Component
global.currentCtorType = "component"
global.currentSrcMode = "wx"
/* mpx inject */ global.currentInject = {
  moduleId: "m11703cf3",
  render: function () {
    this._c("mpxShow", this.mpxShow) || this._c("mpxShow", this.mpxShow) === undefined ? '' : 'display:none;';
    this._i(this._c("listData", this.listData), function (item, index) {
      item;
    });
    this._r();
  }
};
/* harmony import */ var _list_ts_resourcePath_Users_litao_work_GM_gome_src_components_list_list_mpx__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__("./src/components/list/list.ts?resourcePath=/Users/litao/work/GM/gome/src/components/list/list.mpx");
/* empty/unused harmony star reexport */global.currentModuleId
/* script */


/* styles */
__webpack_require__("./node_modules/@mpxjs/webpack-plugin/lib/extractor.js?type=styles&index=0!./node_modules/@mpxjs/webpack-plugin/lib/wxss/loader.js?root=&importLoaders=1&extract=true!./node_modules/@mpxjs/webpack-plugin/lib/style-compiler/index.js?{\"moduleId\":\"m11703cf3\",\"scoped\":false,\"sourceMap\":false}!./node_modules/stylus-loader/index.js!./node_modules/@mpxjs/webpack-plugin/lib/selector.js?type=styles&index=0!./src/components/list/list.mpx?packageName=packShop")

/* json */
__webpack_require__("./node_modules/@mpxjs/webpack-plugin/lib/extractor.js?type=json&index=0!./node_modules/@mpxjs/webpack-plugin/lib/json-compiler/index.js?root=!./node_modules/@mpxjs/webpack-plugin/lib/selector.js?type=json&index=0!./src/components/list/list.mpx?packageName=packShop")

/* template */
__webpack_require__("./node_modules/@mpxjs/webpack-plugin/lib/extractor.js?type=template&index=0!./node_modules/@mpxjs/webpack-plugin/lib/wxml/wxml-loader.js?root=!./node_modules/@mpxjs/webpack-plugin/lib/template-compiler/index.js?{\"usingComponents\":[],\"hasScoped\":false,\"isNative\":false,\"moduleId\":\"m11703cf3\",\"root\":\"\"}!./node_modules/@mpxjs/webpack-plugin/lib/selector.js?type=template&index=0!./src/components/list/list.mpx?packageName=packShop")


/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__("./node_modules/webpack/buildin/global.js")))

/***/ })

},[["./src/components/list/list.mpx?packageName=packShop","bundle"]]]);
```

这里并有调用CreateComponnet方法CreateComponent方法被打包到了bundle.js中
相关代码截图
<img width="767" alt="屏幕快照 2020-08-10 上午11 57 31" src="https://user-images.githubusercontent.com/22835834/89750953-bb796700-db00-11ea-9371-1ad900bb1dcd.png">

注如果将.mpx文件js|ts外部引入改为
```
<script>
//....
</script>
```
的形式则不会有这个问题（这时打包到bundle.js中的代码片段会被打到各自分包下的list.js中）

**Comment by hiyuki** [comment]
确认问题，下个版本修复

**Comment by tliwyl** [comment]
@hiyuki 辛苦大佬

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.2 已修复

**Comment by tliwyl** [comment]
@hiyuki  Thank you very much！！！
