### ISSUE TITLE
[Bug report] 无法集成 thread-loader

### ISSUE THREAD

**Issue by qiwang97** [didi/mpx#807]
```
 {
        test: /\.mpx$/,
        use: [
          {
            loader: 'thread-loader'
          },
          MpxWebpackPlugin.loader(currentMpxLoaderConf)
        ]
      }
```

```
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Cannot read property 'compiler' of undefined
    at PoolWorker.fromErrorObj (/test/node_modules/thread-loader/dist/WorkerPool.js:346:12)
    at /test/node_modules/thread-loader/dist/WorkerPool.js:219:29
    at module.exports (/test/node_modules/@mpxjs/webpack-plugin/lib/utils/get-main-compilation.js:2:22)
    at Object.module.exports (/test/node_modules/@mpxjs/webpack-plugin/lib/loader.js:23:27)

  Build failed with errors.

```

**Comment by hiyuki** [comment]
mpx-loader不是一个纯loader，当中存在side effect，确实不能与thread-loader使用；
以及mpx-loader本身的计算复杂度很低，在构建过程中的耗时占比也非常低，没有必要通过thread-loader提速，一般来讲thread-loader通常是于整体耗时较高的纯loader配合使用，如babel-loader。
