### ISSUE TITLE
wxss里引用 cdn 的图片资源，能否统一添加 cdn 路径？

### ISSUE THREAD

**Issue by SuXW** [didi/mpx#962]
我在工程/build/getRules.js 里面的
const baseRules = [
 {
    test: /\.(png|jpe?g|gif|svg)$/,
    loader: MpxWebpackPlugin.urlLoader({
      name: 'img/[name][hash].[ext]',
     /// 这里添加了publicPath
      publicPath: "https://cunbao-dev.obs.cn-north-1.myhuaweicloud.com/resource/"
    })
  }
]

mpx文件中这样引入：
”<image class="bg-img" src="../common/bg_auth.png"></image>“

提示错误：

ERROR in ./src/pages/auth/文件名称.mpx (./node_modules/@mpxjs/webpack-plugin/lib/extractor.js?{"type":"template","index":0}!./node_modules/@mpxjs/webpack-plugin/lib/wxml/wxml-loader.js?root=/Users/sw/Desktop/Code/wisdomCountry!./node_modules/@mpxjs/webpack-plugin/lib/template-compiler?{"usingComponents":[],"hasScoped":false,"isNative":false,"moduleId":"m79643a66","root":"/Users/sw/Desktop/Code/wisdomCountry"}!./node_modules/@mpxjs/webpack-plugin/lib/selector.js?{"type":"template","index":0}!./src/pages/auth/authorization.mpx)
Module build failed (from ./node_modules/@mpxjs/webpack-plugin/lib/extractor.js):
Error: Cannot find module '../common/bg_auth.png?isStatic=true'
    at webpackMissingModule (!!/Users/sw/Desktop/Code/wisdomCountry/node_modules/@mpxjs/webpack-plugin/lib/content-loader?{"type":"template","index":0}!/Users/sw/Desktop/Code/wisdomCountry/src/pages/auth/authorization.mpx:92:154)
    at Object.<anonymous> (!!/Users/sw/Desktop/Code/wisdomCountry/node_modules/@mpxjs/webpack-plugin/lib/content-loader?{"type":"template","index":0}!/Users/sw/Desktop/Code/wisdomCountry/src/pages/auth/authorization.mpx:92:264)
    at __webpack_require__ (!!/Users/sw/Desktop/Code/wisdomCountry/node_modules/@mpxjs/webpack-plugin/lib/content-loader?{"type":"template","index":0}!/Users/sw/Desktop/Code/wisdomCountry/src/pages/auth/authorization.mpx:21:30)
    at !!/Users/sw/Desktop/Code/wisdomCountry/node_modules/@mpxjs/webpack-plugin/lib/content-loader?{"type":"template","index":0}!/Users/sw/Desktop/Code/wisdomCountry/src/pages/auth/authorization.mpx:85:18
    at Object.<anonymous> (!!/Users/sw/Desktop/Code/wisdomCountry/node_modules/@mpxjs/webpack-plugin/lib/content-loader?{"type":"template","index":0}!/Users/sw/Desktop/Code/wisdomCountry/src/pages/auth/authorization.mpx:88:10)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.exec (/Users/sw/Desktop/Code/wisdomCountry/node_modules/webpack/lib/NormalModule.js:193:12)
    at /Users/sw/Desktop/Code/wisdomCountry/node_modules/@mpxjs/webpack-plugin/lib/extractor.js:193:23
    at /Users/sw/Desktop/Code/wisdomCountry/node_modules/webpack/lib/Compiler.js:343:11
    at /Users/sw/Desktop/Code/wisdomCountry/node_modules/webpack/lib/Compiler.js:681:15
    at eval (eval at create (/Users/sw/Desktop/Code/wisdomCountry/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at /Users/sw/Desktop/Code/wisdomCountry/node_modules/@mpxjs/webpack-plugin/lib/extractor.js:172:5
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/sw/Desktop/Code/wisdomCountry/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/sw/Desktop/Code/wisdomCountry/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/sw/Desktop/Code/wisdomCountry/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/sw/Desktop/Code/wisdomCountry/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
 @ ./src/pages/auth/authorization.mpx 12:0-539

ERROR in ./src/pages/auth/authorization.mpx (./node_modules/@mpxjs/webpack-plugin/lib/content-loader.js?{"type":"template","index":0}!./src/pages/auth/authorization.mpx)
Module not found: Error: Can't resolve '../common/bg_auth.png?isStatic=true' in '/Users/sw/Desktop/Code/wisdomCountry/src/pages/auth'
 @ ./src/pages/auth/authorization.mpx (./node_modules/@mpxjs/webpack-plugin/lib/content-loader.js?{"type":"template","index":0}!./src/pages/auth/authorization.mpx) 1:89-135

  Build failed with errors.

**Comment by Blackgan3** [comment]
publicPathScope: 'all', urlLoader 的配置中加下这个参数试试，默认非style文件中publicPath是不起作用的
